export enum ReportAbuseReason {
    OFFENSIVE_LANGUAGE = 0,
    ITEM_SCAMMING = 1,
    PASSWORD_SCAMMING = 2,
    BUG_ABUSE = 3,
    JAGEX_STAFF_IMPERSONATION = 4,
    ACCOUNT_SHARING_TRADING = 5,
    MACROING = 6,
    MULTI_LOGGING = 7,
    ENCOURAGING_RULE_BREAKING = 8,
    MISUSE_CUSTOMER_SUPPORT = 9
}
